### ISSUE TITLE
Is it a good idea to reuse code during defining various features?

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1231]
Frequently style definitions are repeated for various features, maybe with minor change like text-dy.

Is it a good idea to attempt reuse of this code? See my proposed refactoring at https://github.com/mkoniecz/openstreetmap-carto/commit/1d68047b7cf516fb138a5e35685b9b95eff28c7f

Benefits - lower amount of code, it is obvious that style is repeated.
Problems - may be harder to understand.

I am not 100% sure whatever increased clarity by removal of repetition is greater than what was lost by using slightly more complicated construction (for somebody new - I think that I may now underestimate difficulty for such people).

Maybe it should be limited to cases where style is exactly the same, except zoom level range?

**Comment by pnorman** [comment]
In that specific example, I think it adds clarity.

One option, which I don't like as much would be 
```css
[feature = 'natural_peak'][zoom >= 13],
  [feature = 'natural_volcano'][zoom >= 13],
  [feature = 'natural_saddle'][zoom >= 15],
  [feature = 'natural_cave_entrance'][zoom >= 15] {
    text-name: "[name]";
    text-size: 10;
    text-fill: brown;
    text-dy: 7;
    text-face-name: @book-fonts;
    text-halo-radius: 1;
    text-wrap-width: @standard-wrap-width;
    text-placement: interior;
    [feature = 'natural_volcano'],
    [feature = 'natural_saddle'], {
      text-dy: 7;
    }
    [feature = 'natural_cave_entrance'] {
      text-dy: 11;
    }
  }
```

When possible we should use the cascading part of CartoCSS.
