### ISSUE TITLE
Confusing point=yes selector

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#209]
https://github.com/gravitystorm/openstreetmap-carto/issues/204#issuecomment-25422666 raises the issue of a confusing point=yes selector.

The MSS is

``` css
  /* Hmmm */
  [point = 'yes'][leisure != '']::point,
  [point = 'yes'][landuse != '']::point {
    [zoom >= 15] {
      text-name: "[name]";
      text-size: 9;
      text-fill: #000;
      text-face-name: @book-fonts;
      text-halo-radius: 2;
      text-wrap-width: 10;
    }
  }
```

This applies to features coming from the `planet_osm_point` table and the SQL `'yes'::text as point`.

This adds names for leisure and landuse points, albeit in a confusing way. 

An example is [node 9400233](http://www.openstreetmap.org/browse/node/9400233) in the lower left of 
![17/72122/38595](https://f.cloud.github.com/assets/1190866/1242781/9ce490b6-2a50-11e3-8d43-33e3138ce03b.png). The other name is coming from a [`landuse=recreation_ground`](http://www.openstreetmap.org/browse/way/24415503)

The glow makes this visually distinct from other names but I can't say I've noticed it or realized what it meant. What do we want to do with it?
