### ISSUE TITLE
Chalet icons not rendering

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#236]
We have the mss

``` css
 [amenity = 'chalet'][zoom >= 17]::amenity {
    point-file: url('symbols/chalet.p.16.png');
    point-placement: interior;
  }
```

but no icons showing up

![17/21479/44656](https://f.cloud.github.com/assets/1190866/1350432/a513080a-370a-11e3-98e9-07b599b0bd1c.png)![17/21480/44656](https://f.cloud.github.com/assets/1190866/1350434/a81cdd5a-370a-11e3-9bc7-2b0e727d8f55.png)
