### ISSUE TITLE
historic=fort at z=15

### ISSUE THREAD

**Issue by 501Ghost** [gravitystorm/openstreetmap-carto#4423]
### Expected behavior
I would like to see historic=fort being rendered at zoom level 15, equal to historic=castle. The main reason is that forts often stand out in a landscape and can thus be used as landmarks.

### Actual behavior
historic=fort is currently rendered at zoom level 16 and above. 

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/6315562#map=15/52.0738/5.1801
https://www.openstreetmap.org/way/956146301#map=15/51.2626/4.4605
https://www.openstreetmap.org/way/954093813#map=15/52.0491/5.5536

**Comment by Adamant36** [comment]
> The main reason is that forts often stand out in a landscape and can thus be used as landmarks

I'd be interested to know how many historic forts outside of Europe actually stand out on the landscape. I know in California and the surrounding states most of them are either complete rubble, grassy hills, covered by over growth, or otherwise not that easy to make out if the person isn't specifically looking for them. I'd imagine the same is true for historic forts in Middle East also. Since most have been blown up through multiple wars, exist indiscriminately in hill sides, or have been all but covered with sand and dirt. It wouldn't make sense to render such places at Z15.

**Comment by StyXman** [comment]
> most of them are either complete rubble, grassy hills, covered by over growth...

then filter out by `ruins=yes`?

**Comment by Adamant36** [comment]
> then filter out by ruins=yes?

How many times is `historic=fort` used with `ruins=yes` and where is the usage? I wouldn't have a problem with that if the amount is more then trivial and not just focused in one area.

**Comment by 501Ghost** [comment]
According to Overpass Turbo results, there are over 500 instances of historic=fort + ruins=yes, with uses on all continents. The other 4.3k forts are not tagged with ruins=yes and also exist on all continents. 

Apart from the fact that the landscape around a fort has often been cleared and remade to allow for good visibility and clear lines of fire from the forts, forts are often also tourist spots for people who are interested in military history. 

The https://overpass-turbo.eu/ query for reference: 
```
[out:xml][timeout:100];
nwr["historic"="fort"]["ruins"="yes"];
(._;>;);
out body;
```

**Comment by Adamant36** [comment]
> According to Overpass Turbo results, there are over 500 instances of historic=fort + ruins=yes

Hhhmm, I don't think that's enough times to justify a filter. Plus, I'm kind of sketch on what a ruin is to. It sounds like one of those vague tags isn't worth supporting. That's just my opinion though. Thanks for looking into it. 

> part from the fact that the landscape around a fort has often been cleared and remade to allow for good visibility and clear lines of fire from the forts, forts are often also tourist spots for people who are interested in military history.

That's an extremely Eurocentric way of viewing forts. Plenty of them are no longer or barely visible.  I could care less about rendering the ones that are cleared tourist spots at z15, but by no means are all (or most) forts in the world that way. So they shouldn't all be rendered as if they are.

**Comment by 501Ghost** [comment]
I agree with you that 500 instances of historic=fort + ruins=yes is not worth supporting, but it may still be worth it if the same rule is also applied to castles. I found on Taginfo that out of 47,000 castles on OSM, 4,700 are tagged with ruins=yes. See https://taginfo.openstreetmap.org/tags/historic=castle#combinations for reference. 

I disagree that this is a Eurocentric way to view forts. Forts exist on all continents (see https://taginfo.openstreetmap.org/tags/historic=fort#map ) and many of them are built on hills and have clearly visible defensive structures (such as bastions), which are not at all exclusive to Europe. The ones that are no longer or barely visible are usually tagged with ruins=yes.

**Comment by Adamant36** [comment]
>  The ones that are no longer or barely visible are usually tagged with ruins=yes.

How are they usually tagged with ruins=yes when there's only 500 uses of them being used together out of 5000 or so total forts that are mapped? That's only 10%. Probably the low numbers are because the tag is discouraged and rightly so IMO. Currently mapped or not, there's way more then 500 ruined forts out there. 

> I disagree that this is a Eurocentric way to view forts. Forts exist on all continents (see https://taginfo.openstreetmap.org/tags/historic=fort#map ) and many of them are built on hills and have clearly visible defensive structures

There's a difference between visible, ruined, and "Well visible tourist spots." Which is what you originally said. 

What's Eurocentric is the idea that forts are distinct things with large stone walls and similar things. A lot of the forts in America were nothing more then a few buildings with a wood fence around them. Most people now don't even know they are forts. 

For instance this is a "fort" in Arizona. Most people would just think it's a ranch. 

![fort-verde-az-800](https://user-images.githubusercontent.com/30259065/126158205-b0338df9-5d9f-422a-9287-12dab8554453.jpg)

Fort Dodge in Kansas just looks like an old west suburb in the country side. 

![00093817](https://user-images.githubusercontent.com/30259065/126158365-e9a092e0-9090-4c7f-b984-e30adb7ee7fe.jpg)

This is the "ruins" of a fort in Peru. For all intents and purposes it just looks like some stone walls. There's nothing "fort like" about it. 

![Peru Fortress](https://user-images.githubusercontent.com/30259065/126158907-400bab32-17a5-4fb2-b830-777f5a549d78.jpg)

**Comment by 501Ghost** [comment]
If your opinion about the examples you give is that they are not recognisable as forts, then they're not verifiable (see the OSM good practices) and thus shouldn't be tagged as forts. That's a mapping issue rather than a rendering issue. 

There are also many forts in the USA that **are** clearly distinguisable as forts. For example: 
https://en.wikipedia.org/wiki/Fort_Adams
https://en.wikipedia.org/wiki/Fort_Jefferson_(Florida)
https://en.wikipedia.org/wiki/Fort_Barrancas
and plenty more: https://en.wikipedia.org/wiki/List_of_forts_in_the_United_States

Likewise, India is also full of them: https://en.wikipedia.org/wiki/List_of_forts_in_India

I have never seen that ruins=yes is discouraged. It's a well-documented tag. Could you show me what you mean?

If there are more than 500 ruined forts, then differentiating the rendering will most likely encourage people to map this more frequently.

**Comment by Adamant36** [comment]
> If your opinion about the examples you give is that they are not recognisable as forts, then they're not verifiable (see the OSM good practices) and thus shouldn't be tagged as forts. That's a mapping issue rather than a rendering issue.

They should be tagged as forts because they are forts. How something is tagged has nothing to do with what someone thinks it looks like or not from a distance. If I understand you correctly that seems to be your opinion about how tagging should work though. 


> I have never seen that ruins=yes is discouraged. It's a well-documented and popular tag with 84,5K uses in total. Could you show me what you mean?

According to the Wiki article for ruins=yes "This usage is discouraged by some mappers." Generally speaking the number of uses a tag has isn't that important to rendering. There's plenty of "bad" tags out there with a lot of usage that will never be rendered. 

> If there are more than 500 ruined forts, then differentiating the rendering will most likely encourage people to map this more frequently

Sure, but other things are considered when deciding to render something or not besides just if doing so encourages people to map the tag more. Since any tag that is rendered will be mapped more. So it's kind of a useless, circular reason to render something on it's on own. 

>  I just noticed that ruins=fort has been used ~250 times. These could be the other ruined forts you were talking about. It's a tag I would personally not support, but would document as a tagging mistake of historic=fort + ruins=yes.

Good catch. I'll probably document as a tagging mistake when I have the time if no one else does.

**Comment by StyXman** [comment]
> According to the Wiki article for ruins=yes "This usage is discouraged by some mappers."

I think it's worth to mention that the alternative is `historic=ruins` + `ruins=*`, but for rendering these it's much easier codewise to convert somehow to `historic=*` + `ruins=yes` because the code is simpler: you just define the style for the feature and just add a further filter with only the style change that applies to ruins vs still-standing structures:

```css
  [feature = 'historic_castle'][castle_type != 'stately'][castle_type != 'manor'][zoom >= 15],
  [feature = 'historic_castle'][castle_type = 'stately'][zoom >= 16],
  [feature = 'historic_castle'][castle_type = 'manor'][zoom >= 16],
  [feature = 'historic_manor'][zoom >= 16] {
    marker-file: url('symbols/historic/castle.svg');
    marker-fill: @memorials;
    marker-clip: false;
    [ruins = 'yes'] {
        // some changes
    }
    [castle_type = 'palace'],
    [castle_type = 'stately'] {
      marker-file: url('symbols/historic/palace.svg');
    }
    [castle_type = 'manor'],
    [feature = 'historic_manor'] {
      marker-file: url('symbols/historic/manor.svg');
    }
    [castle_type = 'fortress'],
    [castle_type = 'defensive'],
    [castle_type = 'castrum'],
    [castle_type = 'shiro'],
    [castle_type = 'kremlin'] {
      marker-file: url('symbols/historic/fortress.svg');
    }
  }
```

Just imagine the alternative code.

The new flex import could be used to convert `historic=ruins` + `ruins=*` into `historic=*` + `ruins=yes` _just to simplify the code_. The dangling question would be whether to ignore things tagged like that or not. If discouraging that 'bad tagging' is what it is wanted, then they should be ignored.

**Comment by StyXman** [comment]
> Just imagine the alternative code.

I just did.

```css
  [feature = 'ruins_castle'][castle_type != 'stately'][castle_type != 'manor'][zoom >= 15],
  [feature = 'ruins_castle'][castle_type = 'stately'][zoom >= 16],
  [feature = 'ruins_castle'][castle_type = 'manor'][zoom >= 16],
  [feature = 'ruins_manor'][zoom >= 16] {
    marker-file: url('symbols/historic/castle.svg');
    marker-fill: @memorials;
    marker-clip: false;
    [castle_type = 'palace'],
    [castle_type = 'stately'] {
      marker-file: url('symbols/historic/palace.svg');
    }
    [castle_type = 'manor'],
    [feature = 'historic_manor'] {
      marker-file: url('symbols/historic/manor.svg');
    }
    [castle_type = 'fortress'],
    [castle_type = 'defensive'],
    [castle_type = 'castrum'],
    [castle_type = 'shiro'],
    [castle_type = 'kremlin'] {
      marker-file: url('symbols/historic/fortress.svg');
    }
  }
```

So you basically rewrite the whole block, and probably tweak zoom filters, and markers; yeah, it's not that difficult. Maybe the conversion I mention above is not worth it.
