### ISSUE TITLE
Increased font size causing problems with rendering

### ISSUE THREAD

**Issue by Harvie** [gravitystorm/openstreetmap-carto#4689]
### Expected behavior
Hello,
i had increased font size of important city names in openstreetmap-carto style to improve accessibility for people with poor sight. And it almost works

### Actual behavior
But in 5% cases the text is completely missing on some tiles. I am using mapnik with mod_tile.
I understood that problem is when rendering the tile with such big font, the renderer has to look much further (eg. 2 tiles away) into the gis database, but it does not do that so when rendering that tile it will omit the text.

Google told me that i should increase some buffer size or "extents", so i tried that in `project.mml` file and regenerated the mapnik.xml. The extents were propagated to `mapnik.xml`, but parts of the text labels are still missing. Nothing has changed. Can you please tell me what i am doing wrong?

```yaml
# Various parts to be included later on
_parts:
  # Extents are used for tilemill, and don't actually make it to the generated XML
  extents: &extents
    extent: *world
    srs-name: "900913"
    srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  osm2pgsql: &osm2pgsql
    type: "postgis"
    dbname: "gis"
    key_field: ""
    geometry_field: "way"
    extent: "-80150032,-80150032,80150032,80150032"   # <--- I INCREASED THIS 4 TIMES WITHOUT ANY SUCCESS
```

### Screenshots with links illustrating the problem
![image](https://user-images.githubusercontent.com/276504/190641897-58672dc6-4f5d-4db0-9c92-60c40dddceb2.png)
