### ISSUE TITLE
Incorrect line height for labels containing Tibetan scripts

### ISSUE THREAD

**Issue by ztzthu** [gravitystorm/openstreetmap-carto#4834]
The title pretty much says itself. When a label contains Tibetan scripts, the line height will be excessively large. Normally this is not a problem but when the label is long and has to be wrapped, it will look like two separate lines.

Examples:

https://www.openstreetmap.org/node/3316196457#map=11/29.2654/88.9158 (in Tibet, China)
<img width="185" alt="image" src="https://github.com/gravitystorm/openstreetmap-carto/assets/17211903/f0183899-54c9-4f14-a3fd-af0d9107f301">

https://www.openstreetmap.org/#map=15/26.8644/90.2656 (in Bhutan)
<img width="212" alt="image" src="https://github.com/gravitystorm/openstreetmap-carto/assets/17211903/7b1169ee-6394-413b-ac19-91ac3a44a18f">

While Tibetan, Laos, Thai and Myanmar scripts do need taller line height, this excessive line height is not observed in Laos, Thailand or Myanmar. [A good Tibetan layout example](https://bo.wikipedia.org/wiki/%E0%BD%96%E0%BD%BC%E0%BD%91%E0%BC%8B%E0%BD%80%E0%BE%B1%E0%BD%B2%E0%BC%8B%E0%BD%A6%E0%BE%90%E0%BD%91%E0%BC%8B%E0%BD%A1%E0%BD%B2%E0%BD%82%E0%BC%8D) from the Tibetan wiki page, where approapriate line height is used:

<img width="298" alt="image" src="https://github.com/gravitystorm/openstreetmap-carto/assets/17211903/d706cc93-f3e3-4682-a5ca-088f84e70ee7">

Could be related to #2338, #3512.

**Comment by imagico** [comment]
My understanding is that this is an issue that stems from the design of the font we use (Noto) and not something we can easily adjust from the style specifically for one type of script.  Maybe @sommerluk has more insights.

**Comment by ztzthu** [comment]
Thanks for the insight, seem that indeed the problem lies in the font but not the rendering algorithms. 

The issue #2358 seems to have a lot of good discussions on this topic: In a similar case of Myanmar language, the _Noto Sans Myanmar UI_ font is used instead of _Noto Sans Myanmar_ font. The UI font ensures that the same line height is shared across different languages.

The current Tibetan font is _Noto Serif Tibetan_, and seems that it does not have a UI font version. Can we have a workaround ? The excessive line height does pose a problem i believe.

**Comment by pnorman** [comment]
> The current Tibetan font is _Noto Serif Tibetan_, and seems that it does not have a UI font version. Can we have a workaround ? The excessive line height does pose a problem i believe.

What work-arounds are you aware of? There's very little we can change within OpenStreetMap Carto to fix these kinds of issues.

**Comment by ztzthu** [comment]
One of the possible ways is to use _Jomolhari_ font instead of _Noto Serif Tibetan_ font:

https://fonts.google.com/specimen/Jomolhari/about

It is also liscenced under the Open Font License. As far as I know this is the default fallback font for Tibetan used by Wikipedia, according to their css style sheet:
```css
.mw-parser-output .uchen {
     font-family: "Jomolhari","Uchen","Noto Serif Tibetan Medium","Noto Serif Tibetan","BabelStone Tibetan Slim","Yagpo Tibetan Uni","Noto Sans Tibetan","Microsoft Himalaya","Kailash","DDC Uchen","TCRC Youtso Unicode","Tibetan Machine Uni","Qomolangma-Uchen Sarchen","Qomolangma-Uchen Sarchung","Qomolangma-Uchen Suring","Qomolangma-Uchen Sutung","Qomolangma-Title","Qomolangma-Subtitle","DDC Rinzin","Qomolangma-Woodblock","Qomolangma-Dunhuang"
}
```
