### ISSUE TITLE
RFC for strategy on font management

### ISSUE THREAD

**Issue by imagico** [gravitystorm/openstreetmap-carto#5043]
Since #4606 we have been including a script to download the fonts we use and this way implicitly tell style users they can rely on that taking care of the fonts.  Unfortunately, upstream sources of fonts are volatile and require maintainance of the download locations as well as font file naming (#5013, #4956).  Our current font download script design is not very good for managing that.

This is a proposal how a more sustainable approach could look like.  This is not meant to rule out smaller changes to the existing setup to fix acute issues but to provide a discussion basis for a more long term strategy how to develop this further.

## Proposal

The main ideas are:

* separating the font data from the script functionality
* doing the scripting in python (to match our other scripts)
* storing the data on fonts and their download locations in a YAML file (equally matching our approach in other cases)
* having fallback locations for downloading fonts in case the primary location becomes unavailable. Fallbacks could contain older versions of the fonts if necessary. This would substantially increase reliability of the download process.
* having the script download the fonts as well as generating `fonts.mss` (where the order of entries is crucial - see #4606) - this way we would have a single location where to make changes to the fonts rather than two (`fonts.mss` and `get-fonts.sh`) in different languages.
* having the script by default update existing font files, but overwriting them only after a successful download.

This is just a rough sketch of how this could look like, the details would need to be worked out of course.  Discussion of those as well as of the proposal is welcome.

**Comment by dch0ph** [comment]
Looks a very sensible overall strategy to me.

Am I right in thinking that #4893 would address the acute problem in the meantime?

**Comment by imagico** [comment]
> Am I right in thinking that https://github.com/gravitystorm/openstreetmap-carto/pull/4893 would address the acute problem in the meantime?

That probably depends on what you identify as _the acute problem_.

But yes, sourcing the emoji font from archive.org is probably a reasonably stable solution.  #4893 mainly needs a thorough review.

**Comment by imagico** [comment]
I turned the suggestions into a todo list and marked those implemented by #5052.

Note apart from these principal ideas there is also still the concrete need to source the Noto fonts from an up-to-date source - see #4893.

**Comment by mapmeld** [comment]
This is great! Glad that this is more achievable with the new Python script.

Here's where I'm at:
- I may replace #4893 with a new PR tomorrow -- I'd like to demo support for the newer Noto download links, by fixing my original issue with Arabic like this: https://github.com/gravitystorm/openstreetmap-carto/commit/40542b8b20d
- I wrote an [OSM diary post](https://www.openstreetmap.org/user/mapmeld/diary/405980) about reviewing Unicode block usage across Africa and Asia. It looks like we have great language/script coverage with the exception of Glagolitic in Croatian public art and general misuse (such as Ⰹ to represent [public binoculars](https://en.wikipedia.org/wiki/Tower_viewer)). So I was about to suggest adding Glagolitic. One comment from Croatia said this is very old and rare
- The YAML change does seem more stable than having lists of fonts and lists of exceptions inside of the Python code. I'll have to think on that one

**Comment by imagico** [comment]
Probably should mention the other strategic issue w.r.t. fonts we have - the need to choose fonts based on language because different character designs being mandated by different languages despite using the same unicode code points - see #2208.  This is not directly related to the topics here - but relevant regarding the question if our text rendering sufficiently covers all writings used in OSM world wide.

**Comment by mapmeld** [comment]
I did a mini investigation of #2208. The difficulty is finding CartoCSS which could identify a country, city names within a country, or interpret from text, because CartoCSS doesn't have spatial filters.
- I'd encourage exploring spatial filters because even a simple bounding box could incrementally improve OSM over a large area.
- Taiwanese cities and towns have `is_in:zh` tags which have been there for >10 years. The value always starts with 台灣. I was having difficulty running Kosmtik. The filter we want is something like `[is_in:zh >= '台灣'][is_in:zh <= '台灣鿿'] { ... } ` but I didn't remember or land on the correct syntax.
- If we had access to WikiData beyond the ID, for example https://www.wikidata.org/wiki/Q167061 has a property `located in the administrative territorial entity` linking it to Hong Kong. Without tagging every place on OSM, maybe a script could update the local Postgres database or generate a very long CartoCSS filter `[wikidata=_], [wikidata=_], ...`. There doesn't seem to be any grouping or prefixing where the ID alone tells us it's in HK.
- If the default CJK font for placenames were changed, we could identify Japanese cities by hiragana, katakana, or `wikipedia=ja:__` tags, but this would be detrimental to neighborhoods and other smaller locations

**Comment by mapmeld** [comment]
Re: the YAML for fonts, are you picturing a schema like this?

```yaml
fonts:
  NotoSans:
    regular:
      - https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf
      - [theoretical backup url]
    bold:
      - https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Bold.ttf
    italic:
      - https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Italic.ttf
  NotoSansMyanmarUI:
    regular:
      - https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSansMyanmarUI/NotoSansMyanmarUI-Regular.ttf
```

or more like the CartoCSS

```yaml
book-fonts:
  NotoSans-Regular:
  - https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf
  - [theoretical backup url]
  NotoSansMyanmarUI-Regular:
  - [url]
bold-fonts:
  NotoSans-Bold:
  - [...]
```
