### ISSUE TITLE
Render barriers above highway areas

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#528]
Barriers should be rendered above highway areas.

If not, barriers between highway areas become invisible.

Examples:
http://www.openstreetmap.org/#map=18/52.53296/13.37229

See also https://trac.openstreetmap.org/ticket/2807.

**Comment by pmailkeey** [comment]
This looks like a case of the common breach of common sense that states a rendering order of :
largest areas first to smallest areas;
All lines on top of areas
shorter lines on top of longer lines
points over everything.

As otherwise data will be hidden.

The question is, when will this be implemented ?

**Comment by kocio-pl** [comment]
What is current status of this issue and how difficult it would be to make it work?

**Comment by kocio-pl** [comment]
We have 79 layers, so it's not trivial to know where to start, even though they have clear names. I believe important ones for this issue are (in order of appearance): 
```yaml
  - id: "line-barriers"
  - id: "area-barriers"
  - id: "highway-area-fill"
  - id: "roads-fill"
  - id: "turning-circle-fill"
```
My questions:
1. What is the meaning of layer definitions order - which ones are rendered above?
2. Is it important to have "-" before "id:" in YAML? Some lines miss it.

Wild guess: probably just moving -barriers (probably without touching water-barriers-) after -fill could be the solution?

Hint - current list of all `osm-carto` layers:
```yaml
  - id: "world"
  - id: "coast-poly"
  - id: "builtup"
  - id: "necountries"
  - id: "landcover-low-zoom"
  - id: "landcover"
  - id: "landcover-line"
  - id: "water-lines-casing"
  - id: "water-lines-low-zoom"
  - id: "icesheet-poly"
  - id: "water-areas"
  - id: "landcover-area-symbols"
  - id: "icesheet-outlines"
  - id: "water-lines"
  - id: "water-barriers-line"
  - id: "water-barriers-poly"
  - id: "marinas-area"
  - id: "piers-poly"
  - id: "piers-line"
  - id: "water-barriers-point"
  - id: "bridge"
  - id: "buildings"
  - id: "buildings-major"
  - id: "tunnels"
  - id: "landuse-overlay"
  - id: "line-barriers"
  - id: "cliffs"
  - id: "area-barriers"
  - id: "ferry-routes"
  - id: "turning-circle-casing"
  - id: "highway-area-casing"
    id: "roads-casing"
  - id: "highway-area-fill"
  - id: "roads-fill"
  - id: "turning-circle-fill"
  - id: "aerialways"
  - id: "roads-low-zoom"
  - id: "waterway-bridges"
  - id: "bridges"
  - id: "guideways"
    id: "admin-low-zoom"
  - id: "admin-mid-zoom"
  - id: "admin-high-zoom"
  - id: "power-minorline"
  - id: "power-line"
  - id: "nature-reserve-boundaries"
  - id: "tourism-boundary"
  - id: "trees"
  - id: "country-names"
  - id: "capital-names"
  - id: "state-names"
  - id: "placenames-medium"
  - id: "placenames-small"
  - id: "stations"
  - id: "stations-poly"
  - id: "amenity-points-poly"
  - id: "amenity-points"
  - id: "power-towers"
  - id: "power-poles"
  - id: "roads-text-ref-low-zoom"
  - id: "junctions"
  - id: "bridge-text"
  - id: "roads-text-ref"
  - id: "roads-area-text-name"
  - id: "roads-text-name"
  - id: "paths-text-name"
  - id: "text-poly-low-zoom"
  - id: "text-poly"
  - id: "text-line"
  - id: "text-point"
  - id: "building-text"
  - id: "interpolation"
  - id: "addresses"
  - id: "water-lines-text"
  - id: "ferry-routes-text"
  - id: "admin-text"
  - id: "nature-reserve-text"
  - id: "amenity-low-priority"
  - id: "amenity-low-priority-poly"
```
